# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

##################################################################################################

#IMPORTING LIBRARIES

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog,QFileDialog
from MAB_Graphs import *
from WGC_Graphs import *
from DMDS_Graphs import *

class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(954, 387)
        font = QtGui.QFont()
        font.setPointSize(9)
        Application.setFont(font)

        self.path = None

        self.centralwidget = QtWidgets.QWidget(Application)
        self.centralwidget.setObjectName("centralwidget")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 60, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 70, 431, 41))
        self.lineEdit.setObjectName("lineEdit")

        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(790, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 210, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
                
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(420, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(20, 330, 900, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(310, 150, 161, 41))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setObjectName("dateEdit")
        
        self.label2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label2_2.setGeometry(QtCore.QRect(20, 150, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2_2.setFont(font)
        self.label2_2.setObjectName("label2_2")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 211, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        
        Application.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Application)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 954, 18))
        self.menuBar.setObjectName("menuBar")
        Application.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(Application)
        self.statusbar.setObjectName("statusbar")
        Application.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(Application)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "Json Formatter"))
        self.label1.setText(_translate("Application", "   Select the Configuration File"))
        self.button1.setText(_translate("Application", "Browse"))
        self.button1.clicked.connect(self.clicked)
        self.label2.setText(_translate("Application", "   Select Graph Type"))

        self.comboBox.setItemText(0, _translate("Application", "MAB Graphs"))
        self.comboBox.setItemText(1, _translate("Application", "WGC Graphs"))
        self.comboBox.setItemText(2, _translate("Application", "DMDS Graphs"))

        self.button2.setText(_translate("Application", "Download"))
        self.button2.clicked.connect(self.dwnld_clicked)

        self.dateEdit.setDisplayFormat(_translate("Application", "yyyy-MM-dd"))
        self.label2_2.setText(_translate("Application", "   Select Date(YYYY-MM-dd)"))


        self.actionAbout.setText(_translate("Application", "About"))

    def clicked(self):
        self.label3.setText("Select Excel file")
        self.update()
        self.open_dialog_box()      



    def dwnld_clicked(self):

        content = self.comboBox .currentText()
        temp_var = self.dateEdit.date() 
        var_name = temp_var.toPyDate()

        if content == "MAB Graphs" and self.path != None :
            self.mab_json_fmt = mab_main_funct(self.path,str(var_name))
            with open("MAB_Jsonformat.txt",mode="w") as f:
                f.write(self.mab_json_fmt)
            self.label3.setText("MAB JSON File Downloaded")
            self.update()

        elif content == "WGC Graphs" and self.path != None:
            self.wgc_json_fmt = wgc_main_funct(self.path,str(var_name))
            with open("WGC_Jsonformat.txt",mode="w") as f:
                f.write(self.wgc_json_fmt)
            self.label3.setText("WGC JSON File Downloaded")
            self.update()

        elif content == "DMDS Graphs" and self.path != None:
            self.dmds_json_fmt = dmds_main_funct(self.path,str(var_name))
            with open("DMDS_Jsonformat.txt",mode="w") as f:
                f.write(self.dmds_json_fmt)
            self.label3.setText("DMDS JSON File Downloaded")
            self.update()

        else:
            self.label3.setText("No File Selected")
            self.update()

    def update(self):
        self.label3.adjustSize()

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        self.path = filename[0]
        self.lineEdit.setText(self.path)
        self.label3.setText("")
        


        
    # print(self.checkBox1.isChecked())
    # if self.checkBox1.isChecked():
    #     self.button2.clicked.connect(self.mab_graph)
    # if self.checkBox2.isChecked():
    #     self.button2.clicked.connect(self.wgc_graph)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QMainWindow()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec_())
